[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
build_flags =
	-D BOARD_HAS_PSRAM
lib_deps =
	https://github.com/Kopunk/ESP32-BLE-Combo.git
